version: 1.2
tools:
  - subclass: CWL
    primaryDescriptorPath: /md5sum/dockstore-tool-md5sum.cwl
    testParameterFiles:
      - /md5sum/test-parameter-file-where-you-upload-own-md5sum-file.json
      - /md5sum/test-parameter-file-with-https-file.json
      - /md5sum/test-parameter-file-with-s3.json
    name: md5sum_test
    authors:
      - name: Flynn Hembroff
workflows:
  - subclass: CWL
    name: S3_DEMO
    primaryDescriptorPath: /s3demo/s3demo.cwl
    testParameterFiles:
      - /s3demo/inputs.json
    authors:
      - name: Flynn Hembroff
  - subclass: CWL
    name: nontrivial
    primaryDescriptorPath: /nontrivial/nontrivial.cwl
    testParameterFiles:
      - /nontrivial/inputs.json
    authors:
      - name: Flynn Hembroff
  - subclass: CWL
    name: manyJobs
    primaryDescriptorPath: /manyjobs/manyjobs.cwl
    testParameterFiles:
      - /manyjobs/inputs.json
      - /manyjobs/inputs.tiny.json
    authors:
      - name: Flynn Hembroff
  - subclass: CWL
    name: words
    primaryDescriptorPath: /words/main.cwl
    testParameterFiles:
      - /words/inputs.json
    authors:
      - name: Flynn Hembroff